### ISSUE TITLE
Commands do not trigger action

### ISSUE THREAD

**Issue by andi-5000** [MinLL/MinAI#55]
Not sure if this is the right place to put this - I tried contacting MinLL via dm on Nexus but no reply yet.
Various command such as -undress- or -sex- correctly become part of the NPC replies when appropriate. But they do not result in any action (such as undressing or triggering a sex scene in SL). How to resolve this or what additional requirements are there besides the mandatory ones? (Additional info: SexLab is running fine otherwise, including further mods all using SL. OStim is not installed, since using both at the same time would also require moving vom FNIS to Nemesis).

**Comment by MinLL** [comment]
Hey - Take a look at the FAQ, and see if it addresses your issue.

**Comment by andi-5000** [comment]
Yes, sorry, found out that Papyrus Tweaks was missing. Did not see it on Nexus a requirement and when I came here I did no bother to re-read the requirements. My bad. Solved.
