### ISSUE TITLE
[Bug] Bug between MinAI & Paradise Halls Reborn.

### ISSUE THREAD

**Issue by monk-insane** [MinLL/MinAI#93]
Sometimes, when keywords are used by a PAHE slave given a custom name either via PAHE's automatic renaming function or manually via PAHE MCM, the slave's name gets blanked.

This causes you to be unable to interact with the slave at all. Easily fixed by going into PAHE MCM and giving the slave follower a name again, but would obviously be nice if it didn't happen. 

Seems to happen more often when the -molest- keyword is used, so it may be a weird interaction between PAHE, MinAI and SLHH
[loadorder.txt](https://github.com/user-attachments/files/17847677/loadorder.txt)

**Comment by monk-insane** [comment]
Definitely a interaction between Paradise Halls - MinAI - and SLHH.

Only happens with Molest keyword.

**Comment by MinLL** [comment]
I don't see how this could be caused by MinAI. MinAI only reads the NPC's name in-game, it does not write to it. Could be something with SLHH though.

The molest keyword is just invoking SLHH. Likely something on that end.

**Comment by monk-insane** [comment]
Definitely possible - have not seen it happen with the normal SLHH interaction though (Bumping into them and triggering SLHH that way.)  But I've yet to see a slave  do that - i think they get excluded from valid NPCs for SLHH Collision trigger.

**Comment by monk-insane** [comment]
LOVE the mod - by the way. Excellent work.

**Comment by monk-insane** [comment]
I can for the life of me not get the PAHE slaves to trigger SLHH the normal mway - I suspect that SLHH excludes PAHE slaves for a reason. So I suspect you're right that it's a SLHH thing.

No matter - minor annoyance anyways. I'm closing this as I don't believe it's a MinAI bug - but a SLHH one.
